// Mock/demo data — used when backend is unavailable
// model3dUrl points to real GLB files in /public/models/

export const MOCK_JEWELLERY = [
  { _id:'j001', name:'Royal Kundan Jhumka', category:'earring', subcategory:'jhumka',
    material:'gold', price:18500, currency:'INR',
    description:'Traditional kundan jhumka earrings with intricate meenakari work.',
    images:[], model3dUrl:'/models/earrings/kundan_jhumka.glb',
    arConfig:{scale:0.8,offsetX:0,offsetY:-0.02,offsetZ:0,anchorLandmark:'left_ear'},
    style:'bridal', occasion:['wedding','festival'], colorTone:'warm',
    gemstones:['kundan','ruby'], tags:['traditional','bridal','festive'],
    rating:4.8, reviewCount:245, inStock:true },
  { _id:'j002', name:'Diamond Solitaire Studs', category:'earring', subcategory:'stud',
    material:'diamond', price:45000, currency:'INR',
    description:'Certified diamond stud earrings in 18K white gold.',
    images:[], model3dUrl:'/models/earrings/diamond_stud.glb',
    arConfig:{scale:0.4,offsetX:0,offsetY:-0.01,offsetZ:0,anchorLandmark:'left_ear'},
    style:'minimalist', occasion:['daily','office','party'], colorTone:'cool',
    gemstones:['diamond'], tags:['diamond','stud','minimalist'],
    rating:4.9, reviewCount:189, inStock:true },
  { _id:'j003', name:'Silver Oxidized Hoop', category:'earring', subcategory:'hoop',
    material:'silver', price:1299, currency:'INR',
    description:'Oxidized silver hoop earrings with tribal pattern.',
    images:[], model3dUrl:'/models/earrings/silver_hoop.glb',
    arConfig:{scale:0.9,offsetX:0,offsetY:0,offsetZ:0,anchorLandmark:'left_ear'},
    style:'contemporary', occasion:['daily','casual'], colorTone:'cool',
    gemstones:[], tags:['silver','casual','everyday'],
    rating:4.3, reviewCount:562, inStock:true },
  { _id:'j004', name:'Rose Gold Floral Drops', category:'earring', subcategory:'drop',
    material:'rose-gold', price:8900, currency:'INR',
    description:'Elegant rose gold drop earrings with floral design.',
    images:[], model3dUrl:'/models/earrings/rose_gold_drop.glb',
    arConfig:{scale:0.7,offsetX:0,offsetY:-0.015,offsetZ:0,anchorLandmark:'left_ear'},
    style:'contemporary', occasion:['party','date'], colorTone:'warm',
    gemstones:['tourmaline'], tags:['rose-gold','floral','romantic'],
    rating:4.6, reviewCount:98, inStock:true },
  { _id:'j005', name:'Pearl Chandbali Earrings', category:'earring', subcategory:'chandbali',
    material:'gold', price:12000, currency:'INR',
    description:'Classic chandbali earrings with freshwater pearl drops.',
    images:[], model3dUrl:'/models/earrings/pearl_chandbali.glb',
    arConfig:{scale:0.85,offsetX:0,offsetY:-0.02,offsetZ:0,anchorLandmark:'left_ear'},
    style:'traditional', occasion:['wedding','festival'], colorTone:'warm',
    gemstones:['pearl'], tags:['pearl','chandbali','traditional'],
    rating:4.7, reviewCount:134, inStock:true },
  { _id:'j006', name:'Emerald Polki Earrings', category:'earring', subcategory:'polki',
    material:'gold', price:35000, currency:'INR',
    description:'Uncut diamond polki earrings with natural emeralds.',
    images:[], model3dUrl:'/models/earrings/emerald_polki.glb',
    arConfig:{scale:0.9,offsetX:0,offsetY:-0.025,offsetZ:0,anchorLandmark:'left_ear'},
    style:'bridal', occasion:['wedding','sangeet'], colorTone:'warm',
    gemstones:['diamond','emerald'], tags:['polki','bridal','luxury'],
    rating:4.9, reviewCount:67, inStock:true },
  { _id:'j007', name:'Classic Diamond Pendant', category:'necklace', subcategory:'pendant',
    material:'diamond', price:55000, currency:'INR',
    description:'Solitaire diamond pendant in 18K white gold.',
    images:[], model3dUrl:'/models/necklaces/diamond_pendant.glb',
    arConfig:{scale:0.6,offsetX:0,offsetY:0.05,offsetZ:0,anchorLandmark:'neck_center'},
    style:'minimalist', occasion:['party','office','wedding'], colorTone:'cool',
    gemstones:['diamond'], tags:['diamond','pendant','gifting'],
    rating:4.9, reviewCount:312, inStock:true },
  { _id:'j008', name:'Kundan Meenakari Choker', category:'necklace', subcategory:'choker',
    material:'gold', price:28000, currency:'INR',
    description:'Vibrant meenakari choker with kundan setting.',
    images:[], model3dUrl:'/models/necklaces/kundan_choker.glb',
    arConfig:{scale:0.95,offsetX:0,offsetY:0.03,offsetZ:0,anchorLandmark:'neck_center'},
    style:'bridal', occasion:['wedding','engagement'], colorTone:'warm',
    gemstones:['kundan'], tags:['kundan','bridal','festive'],
    rating:4.7, reviewCount:156, inStock:true },
  { _id:'j009', name:'Rose Gold Heart Necklace', category:'necklace', subcategory:'pendant',
    material:'rose-gold', price:9500, currency:'INR',
    description:'Delicate rose gold heart pendant with ruby accent.',
    images:[], model3dUrl:'/models/necklaces/rose_heart.glb',
    arConfig:{scale:0.5,offsetX:0,offsetY:0.04,offsetZ:0,anchorLandmark:'neck_center'},
    style:'contemporary', occasion:['anniversary','gifting','daily'], colorTone:'warm',
    gemstones:['ruby'], tags:['heart','rose-gold','gifting'],
    rating:4.6, reviewCount:278, inStock:true },
  { _id:'j010', name:'Solitaire Engagement Ring', category:'ring', subcategory:'solitaire',
    material:'diamond', price:120000, currency:'INR',
    description:'Classic 4-prong solitaire engagement ring. 1 carat certified diamond.',
    images:[], model3dUrl:'/models/rings/solitaire_engagement.glb',
    arConfig:{scale:0.5,offsetX:0,offsetY:0,offsetZ:0,anchorLandmark:'ring_finger_right'},
    style:'minimalist', occasion:['engagement','wedding'], colorTone:'cool',
    gemstones:['diamond'], tags:['engagement','luxury'],
    rating:5.0, reviewCount:87, inStock:true },
  { _id:'j011', name:'Gold Maharani Ring', category:'ring', subcategory:'cocktail',
    material:'gold', price:22000, currency:'INR',
    description:'Bold cocktail ring with rubies and emeralds in 22K gold.',
    images:[], model3dUrl:'/models/rings/maharani_ring.glb',
    arConfig:{scale:0.55,offsetX:0,offsetY:0,offsetZ:0,anchorLandmark:'ring_finger_right'},
    style:'traditional', occasion:['wedding','festival'], colorTone:'warm',
    gemstones:['ruby','emerald'], tags:['gold','cocktail','statement'],
    rating:4.7, reviewCount:143, inStock:true },
  { _id:'j012', name:'Stackable Bands Set', category:'ring', subcategory:'band',
    material:'rose-gold', price:15000, currency:'INR',
    description:'Set of 3 stackable rose gold bands with diamond accents.',
    images:[], model3dUrl:'/models/rings/stackable_bands.glb',
    arConfig:{scale:0.48,offsetX:0,offsetY:0,offsetZ:0,anchorLandmark:'ring_finger_right'},
    style:'contemporary', occasion:['daily','casual'], colorTone:'warm',
    gemstones:['diamond'], tags:['stackable','rose-gold','trendy'],
    rating:4.8, reviewCount:267, inStock:true },
  { _id:'j013', name:'Diamond Tennis Bracelet', category:'bracelet', subcategory:'tennis',
    material:'diamond', price:95000, currency:'INR',
    description:'Exquisite tennis bracelet with 3 carats of round brilliant diamonds.',
    images:[], model3dUrl:'/models/bracelets/diamond_tennis.glb',
    arConfig:{scale:0.7,offsetX:0,offsetY:0,offsetZ:0,anchorLandmark:'left_wrist'},
    style:'minimalist', occasion:['wedding','party','gifting'], colorTone:'cool',
    gemstones:['diamond'], tags:['diamond','tennis','luxury'],
    rating:4.9, reviewCount:45, inStock:true },
  { _id:'j014', name:'Gold Kada Bracelet', category:'bracelet', subcategory:'kada',
    material:'gold', price:42000, currency:'INR',
    description:'Traditional 22K gold kada with engraved floral patterns.',
    images:[], model3dUrl:'/models/bracelets/gold_kada.glb',
    arConfig:{scale:0.8,offsetX:0,offsetY:0,offsetZ:0,anchorLandmark:'left_wrist'},
    style:'traditional', occasion:['wedding','festival'], colorTone:'warm',
    gemstones:[], tags:['kada','gold','traditional'],
    rating:4.7, reviewCount:198, inStock:true },
  { _id:'j015', name:'Diamond Nose Pin', category:'nose-ring', subcategory:'pin',
    material:'diamond', price:8500, currency:'INR',
    description:'Tiny brilliant diamond nose pin in 18K gold.',
    images:[], model3dUrl:'/models/nosering/diamond_pin.glb',
    arConfig:{scale:0.2,offsetX:-0.015,offsetY:-0.005,offsetZ:0,anchorLandmark:'left_nostril'},
    style:'minimalist', occasion:['daily','office'], colorTone:'cool',
    gemstones:['diamond'], tags:['nose-pin','minimalist','everyday'],
    rating:4.8, reviewCount:489, inStock:true },
  { _id:'j016', name:'Gold Nath Nose Ring', category:'nose-ring', subcategory:'nath',
    material:'gold', price:15000, currency:'INR',
    description:'Bridal nath with pearl drops and kundan work.',
    images:[], model3dUrl:'/models/nosering/gold_nath.glb',
    arConfig:{scale:0.9,offsetX:-0.02,offsetY:0,offsetZ:0,anchorLandmark:'left_nostril'},
    style:'bridal', occasion:['wedding'], colorTone:'warm',
    gemstones:['pearl','kundan'], tags:['nath','bridal','wedding'],
    rating:4.7, reviewCount:78, inStock:true },
  { _id:'j017', name:'Om Gold Pendant', category:'pendant', subcategory:'religious',
    material:'gold', price:6500, currency:'INR',
    description:'Sacred Om symbol pendant in 22K gold with diamond accents.',
    images:[], model3dUrl:'/models/pendants/om_pendant.glb',
    arConfig:{scale:0.5,offsetX:0,offsetY:0.05,offsetZ:0,anchorLandmark:'neck_center'},
    style:'fusion', occasion:['daily','religious','gifting'], colorTone:'warm',
    gemstones:['diamond'], tags:['om','gold','religious'],
    rating:4.8, reviewCount:567, inStock:true },
  { _id:'j018', name:'Butterfly Silver Pendant', category:'pendant', subcategory:'fashion',
    material:'silver', price:1899, currency:'INR',
    description:'Dainty butterfly pendant in sterling silver with rainbow sapphires.',
    images:[], model3dUrl:'/models/pendants/butterfly_pendant.glb',
    arConfig:{scale:0.45,offsetX:0,offsetY:0.04,offsetZ:0,anchorLandmark:'neck_center'},
    style:'contemporary', occasion:['casual','gifting'], colorTone:'cool',
    gemstones:['sapphire'], tags:['butterfly','silver','cute'],
    rating:4.5, reviewCount:342, inStock:true },
];

export const MOCK_CATEGORIES = ['earring','necklace','ring','bracelet','nose-ring','bangle','pendant'];

export const MATERIAL_EMOJI = {
  gold:'🟡', silver:'⚪', diamond:'💎',
  'rose-gold':'🌸', 'white-gold':'⬜',
  platinum:'🔘', pearl:'🤍', gemstone:'💠'
};

export const formatPrice = (price, currency = 'INR') =>
  new Intl.NumberFormat('en-IN', { style:'currency', currency, maximumFractionDigits:0 }).format(price);

export const renderStars = (rating) => {
  const full = Math.floor(rating);
  const half = rating % 1 >= 0.5 ? 1 : 0;
  return '★'.repeat(full) + (half ? '½' : '') + '☆'.repeat(5 - full - half);
};
